### ISSUE TITLE
When Exporting From a Profile With a Large Number of Tracks, Site Crashes.

### ISSUE THREAD

**Issue by IAmEchino** [radusuciu/savesoundcloud#13]
Sorry.

This is my account, BTW: 

https://soundcloud.com/echinoofficial

I wasn't doing it maliciously, I just guess your site wasn't able to handle such a large request. Sorry again!

I'm not a programmer, but maybe you could make it so that the program takes its time when processing larger profiles?

Echino

**Comment by radusuciu** [comment]
Thank you for the report! Your account isn't abnormally large so I definitely think there is an underlying issue. I'll take a look this week and get back to you.

**Comment by radusuciu** [comment]
I can confirm that looking up your profile is a very reliable way of making the tiny digitalocean droplet I'm using consume all of its memory on the way to becoming completely unresponsive. I haven't had time to delve into why this is happening.

**Comment by radusuciu** [comment]
Hey, the issue was actually related to comments - if you have 200 or more comments, a mistake I made in putting together url parameters meant that an infinite loop would be triggered, which would eat up all the memory on the server. Thanks!

**Comment by IAmEchino** [comment]
Oh hey! I seem to have missed this reply for over a month. 

No problem! Glad you figured out what the issue was! I'll let you know if I find anything else.

Edit: Also the site is down at time of writing. Weird.
